use readlink

diff --git a/bin/fx b/bin/fx
--- a/bin/fx
+++ b/bin/fx
@@ -3,15 +3,16 @@
 # https://fx.wtf/install
 
 # TODO handle passing flags
-if [[ -r "${1:-}" ]] ; then
+file="$(readlink -f "${1:?Usage: fx <file>}")"
+if [[ -r "$file" ]] ; then
   docker run \
     -u "$(id -u):$(id -g)" \
     -it \
     --rm \
-    -v "$1:/file.json:ro" \
+    -v "$file:/file.json:ro" \
     -e FX_THEME=3 \
     antonmedv/fx "/file.json"
 else
-  echo "Usage: fx <file>" >&2
+  echo "ERROR: ${1:-} not found" >&2
   exit 1
 fi
